typography_spectrum: 0.2654479828197509
color:
  brandStrength: 0.9645847408100963
  lightness: 0.5288644458632916
  saturation: 0.5096669914200902
  rhythmicContrast: 0.2939132263418287
  brandColors:
    - '#070101'
    - '#FEFAF9'
    - '#A5A1A0'
    - '#494544'
    - '#D3CFCE'
opengraph:
  type: Page
  appId: donnybaileyseagraves
layout_spectrum: 0.17166997492313385
author:
  name: Donny Seagraves
  email: donnyseagraves@gmail.com
  url: thegrid.ai/donny-bailey-seagraves
name: Donny Bailey Seagraves
title: Author
