typography_spectrum: 0.019284642999991775
color:
  brandStrength: 0.6001719702035189
  lightness: 0.8665061651263386
  saturation: 0.17550807748921216
  rhythmicContrast: 0.6222493331879377
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
opengraph:
  type: Page
  appId: donnybaileyseagraves
layout_spectrum: 0.4677843807730824
author:
  name: Donny Seagraves
  email: donnyseagraves@gmail.com
  url: thegrid.ai/donny-bailey-seagraves
name: Donny Bailey Seagraves
title: Welcome
