typography_spectrum: 0.18106642784550786
color:
  brandStrength: 0.7198931374587119
  lightness: 0.47088748635724187
  saturation: 0.2767835115082562
  rhythmicContrast: 0.45806905371136963
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
opengraph:
  type: Page
  appId: donnybaileyseagraves
layout_spectrum: 0.7044983736705035
author:
  name: Donny Seagraves
  email: donnyseagraves@gmail.com
  url: thegrid.ai/donny-bailey-seagraves
name: Donny Bailey Seagraves
title: Welcome
