typography_spectrum: 0.2654479828197509
color:
  brandStrength: 0.9645847408100963
  lightness: 0.5288644458632916
  saturation: 0.5096669914200902
  rhythmicContrast: 0.2939132263418287
  brandColors:
    - '#070101'
    - '#FEFAF9'
    - '#A5A1A0'
    - '#494544'
    - '#D3CFCE'
opengraph:
  type: Page
  appId: donnybaileyseagraves
layout_spectrum: 0.17166997492313385
author:
  name: Donny Seagraves
  email: donnyseagraves@gmail.com
  url: thegrid.ai/donny-bailey-seagraves
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6df13d03-f72f-4a01-b102-ffd0d3a307bb.jpg
name: Donny Bailey Seagraves
navigation:
  - name: About me
    id: 38a55448-1262-4631-85eb-676a4a873309
    type: content
  - name: Writing
    id: 0425f84c-38d3-44b8-b95d-68153b083afd
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/887c3979-91c2-49e9-b659-589d43e4f234.png
title: Author
